#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}S

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/skr_pro
$CFGDIR/accessories/dummy-extruder
$CFGDIR/accessories/tmc5160
$CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/no-dual-endstops
$CFGDIR/accessories/laser-32bit

opt_set X_DRIVER_TYPE  "TMC5160"
opt_set Y_DRIVER_TYPE  "TMC5160"
opt_set Z_DRIVER_TYPE  "TMC5160"
opt_set E0_DRIVER_TYPE  "TMC5160"

export PLATFORMIO_ENV=BIGTREE_SKR_PRO
